version: '2'

services:
  app:
    build: .
    links:
      - redis:redis
      - memcached:memcached
    volumes:
      - /var/www/html
    ports:
      - "5000:80"

  redis:
    image: redis
    restart: always

  memcached:
    image: memcached
    restart: always
