version: '2'

services:
  app:
    build: .
    links:
      - redis:redis
      - memcached:memcached
      - mysql:mysql
    volumes:
      - /var/www/html
    ports:
      - "5000:80"

  redis:
    image: redis
    restart: always

  memcached:
    image: memcached
    restart: always

  mysql:
    image: mysql:latest
    restart: always
    command: "mysql -u root -p -e CREATE DATABASE locker"
    volumes:
      - /var/lib/mysql