version: '2'

services:
  app:
    build: .
    links:
      - redis
      - memcached
      - mysql
    volumes:
      - /var/www/html
    ports:
      - "5000:80"

  redis:
    image: redis
    restart: always

  memcached:
    image: memcached
    restart: always

  mysql:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: in_memory_list
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker