redis_parameters:
  scheme: 'tcp'
  host: 'redis'
  port: '6379'
  options:
    profile: '3.2'

memcached_parameters:
  host: 'memcached'
  port: '11211'

pdo_parameters:
  driver: 'mysql'
  host: 'mysql'
  username: 'root'
  password: ~
  database: 'locker'
  port: '3306'
  options: ~