<?php

use InMemoryList\Command\FlushCommand;
use InMemoryList\Tests\BaseTestCase;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Tester\CommandTester;

class FlushCommandTest extends BaseTestCase
{
    /**
     * @var Application
     */
    private $app;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->app = new Application();
    }

    /**
     * @test
     */
    public function it_displays_correctly_memcached_flush_message()
    {
        $this->app->add(new FlushCommand('memcached', $this->memcached_parameters));
        $command = $this->app->find('iml:cache:flush');

        $commandTester = new CommandTester($command);
        $commandTester->execute([
            'command' => $command->getName(),
        ]);

        $output = $commandTester->getDisplay();

        $this->assertContains('[memcached] Cache was successful flushed.', $output);
    }

    /**
     * @test
     */
    public function it_displays_correctly_apcu_flush_message()
    {
        $this->app->add(new FlushCommand('apcu'));
        $command = $this->app->find('iml:cache:flush');

        $commandTester = new CommandTester($command);
        $commandTester->execute([
            'command' => $command->getName(),
        ]);

        $output = $commandTester->getDisplay();

        $this->assertContains('[apcu] Cache was successful flushed.', $output);
    }

    /**
     * @test
     */
    public function it_displays_correctly_redis_flush_message()
    {
        $this->app->add(new FlushCommand('redis', $this->redis_parameters));
        $command = $this->app->find('iml:cache:flush');

        $commandTester = new CommandTester($command);
        $commandTester->execute([
            'command' => $command->getName(),
        ]);

        $output = $commandTester->getDisplay();

        $this->assertEquals('redis', $command->getDriver());
        $this->assertEquals($this->redis_parameters['host'], $command->getParameters()['host']);
        $this->assertEquals($this->redis_parameters['port'], $command->getParameters()['port']);
        $this->assertContains('[redis] Cache was successful flushed.', $output);
    }
}
