<?php

use InMemoryList\Command\StatisticsCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Tester\CommandTester;
use PHPUnit\Framework\TestCase;

class StatisticsCommandTest extends TestCase
{
    /**
     * @var Application
     */
    private $app;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->app = new Application();
        $this->app->add(new StatisticsCommand());
    }

    /**
     * @test
     */
    public function it_displays_correctly_apcu_statistics()
    {
        $command = $this->app->find('iml:cache:statistics');

        $commandTester = new CommandTester($command);
        $commandTester->execute([
            'command' => $command->getName(),
            'driver' => 'apcu',
        ]);

        $output = $commandTester->getDisplay();

        $this->assertContains('num_slots', $output);
        $this->assertContains('ttl', $output);
        $this->assertContains('num_hits', $output);
        $this->assertContains('num_misses', $output);
        $this->assertContains('num_inserts', $output);
        $this->assertContains('num_entries', $output);
        $this->assertContains('expunges', $output);
        $this->assertContains('start_time', $output);
        $this->assertContains('start_time', $output);
        $this->assertContains('mem_size', $output);
        $this->assertContains('memory_type', $output);
        $this->assertContains('deleted_list', $output);
        $this->assertContains('slot_distribution', $output);
    }

    /**
     * @test
     */
    public function it_displays_correctly_memcached_statistics()
    {
        $command = $this->app->find('iml:cache:statistics');

        $commandTester = new CommandTester($command);
        $commandTester->execute([
            'command' => $command->getName(),
            'driver' => 'memcached',
        ]);

        $output = $commandTester->getDisplay();

        $this->assertContains('127.0.0.1:11211', $output);
    }

    /**
     * @test
     */
    public function it_displays_correctly_redis_statistics()
    {
        $command = $this->app->find('iml:cache:statistics');

        $commandTester = new CommandTester($command);
        $commandTester->execute([
            'command' => $command->getName(),
            'driver' => 'redis',
        ]);

        $output = $commandTester->getDisplay();

        $this->assertContains('Clients', $output);
        $this->assertContains('Cluster', $output);
        $this->assertContains('CPU', $output);
        $this->assertContains('Memory', $output);
        $this->assertContains('Persistence', $output);
        $this->assertContains('Replication', $output);
        $this->assertContains('Server', $output);
        $this->assertContains('Stats', $output);
    }
}